// Generated by CoffeeScript 1.11.1
(function() {
  var lastname, main, name;

  name = 'Ruth';

  lastname = 'Mc';

  main = document.getElementById('main');

  main.innerHTML = "Hello " + (name + " " + lastname);

}).call(this);
